### ISSUE TITLE
Enhancement: simple API for the webring links

### ISSUE THREAD

**Issue by rosswintle** [jackmcdade/weird-wide-webring#14]
Is it useful to have a simple API for getting the webring links?

e.g. if I get https://weirdwidewebring.net/links.html

I get back a simple unstyled list that I can use:

```html
<ul>
  <li><a href="https://weirdwidewebring.net/prev.html?ref=yourdomain.com">Previous site</a></li>
    <li><a href="https://weirdwidewebring.net/next.html?ref=yourdomain.com">Next site</a></li>
   <!-- And so on -->
</ul>
```

and if I visit https://weirdwidewebring.net/links.json I get:

```javascript
{
  "previous": "https://weirdwidewebring.net/prev.html?ref=yourdomain.com",
  "next": "https://weirdwidewebring.net/next.html?ref=yourdomain.com",
  // etc
}
```

There might be security things I've not thought of with this (you probably want to be in control of links on your own site, right?).

And we'll need to detect the referrer. Hmm...maybe this won't work on static hosting.

Gonna leave this here to think about. Is there a way to do this?

**Comment by rosswintle** [comment]
Sorry for thinking out loud - this isn't the kind of issue you want.

Seems you try to detect the referrer? So we can omit the `?ref=yourdomain.com` and it still works? So we COULD return theses?

I'll see if I can make a PR. I'm sure there's some reason NOT to do this.

**Comment by jackmcdade** [comment]
I _do_ try to detect the referrer actually, but it's not 100% reliable so you can add your own `ref` in there. Though now that you mention it, maybe it's best to _always_ detect so people can't manipulate the ref?

**Comment by rosswintle** [comment]
When matching the query string for next/prev, I think you need to chop the path and query string off the referrer too. I'm getting stuck after one hop.
